Fix bug 751923 - Failure during event creation [Exception 'TypeError: aItem.calendar.isInvitation is not a function' in calProviderUtils.jsm] (regression). r=mmecca
--HG--
extra : rebase_source : 2d7769f561bf26187c9d74453d97ad126789c3f6