Fix bug 788004 - No email send after invitation creation if offline cache is enabled  [Exception... "'TypeError: aItem.calendar.canNotify is not a function' when calling method: [calIOperationListener::onOperationComplete]" (regression). r=philipp
--HG--
extra : rebase_source : e8e8f93d1fabb7bb39065a979fc4795ad41d2170